AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  hotelito-go1.x
  
  SAM Template for hotelito-go1.x

# More info about Globals: https://github.com/awslabs/serverless-application-model/blob/master/docs/globals.rst
Globals:
  Function:
    Timeout: 5
    MemorySize: 128

Parameters:
  Environment:
    Type: String
    Default: 'production'
  ApplicationName:
    Type: String
    Default: 'hotelito-app'
  LogLevel:
    Type: String
    Default: 'debug'
    AllowedValues:
          - error
          - warn
          - info
          - debug
          - trace
  S3BucketMap3CXRoomExtClBedsRoomId:
    Type: String
    Default: 'hotelito-app-3cxroomextension-cloudbedsroomid'


Resources:
  BucketFor3CXRoomExtensionCloudbedsRoomIdMap:
      Type: AWS::S3::Bucket
      Properties:
        BucketName: hotelito-app-3cxroomextension-cloudbedsroomid

  InitialAuthorizationFunction:
      Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
      Properties:
        CodeUri: hotelito/cloudbeds/initial_authorization
        Handler: main
        Runtime: go1.x
        Architectures:
          - x86_64
        Events:
          GetInitialAuthorization:
            Type: Api # More info about API Event Source: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#api
            Properties:
              Path: /api/v1/
              Method: GET
        Policies:
          - Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action:
                  - ssm:PutParameter
                  - ssm:GetParameter
                Resource: !Sub 'arn:aws:ssm:${AWS::Region}:*:parameter/${ApplicationName}/${Environment}/*'
        Environment: # More info about Env Vars: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#environment-object
          Variables:
            ENVIRONMENT: !Ref Environment
            APPLICATION_NAME: !Ref ApplicationName
            LOG_LEVEL: !Ref LogLevel


  CallbackFunction:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      CodeUri: hotelito/cloudbeds/oauth2callback/
      Handler: main
      Runtime: go1.x
      Architectures:
        - x86_64
      Events:
        GetCallback:
          Type: Api # More info about API Event Source: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#api
          Properties:
            Path: /api/v1/callback
            Method: GET
      Policies:
        - Version: '2012-10-17'
          Statement:
            - Effect: Allow
              Action:
                - ssm:PutParameter
                - ssm:DeleteParameter
                - ssm:GetParameter
              Resource: !Sub 'arn:aws:ssm:${AWS::Region}:*:parameter/${ApplicationName}/${Environment}/*'
      Environment: # More info about Env Vars: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#environment-object
        Variables:
            ENVIRONMENT: !Ref Environment
            APPLICATION_NAME: !Ref ApplicationName
            LOG_LEVEL: !Ref LogLevel

  3CXLookupByNumberFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: hotelito/3cx/lookupbynumber/
      Handler: main
      Runtime: go1.x
      Architectures:
        - x86_64
      Events:
        GetLookupByNumber:
          Type: Api
          Properties:
            Path: /api/v1/3cx/lookupbynumber
            Method: GET
      Policies:
        - Version: '2012-10-17'
          Statement:
            - Effect: Allow
              Action:
                - ssm:GetParameter
                - ssm:PutParameter
                - ssm:DeleteParameter
              Resource: !Sub 'arn:aws:ssm:${AWS::Region}:*:parameter/${ApplicationName}/${Environment}/*'
      Environment:
        Variables:
            ENVIRONMENT: !Ref Environment
            APPLICATION_NAME: !Ref ApplicationName
            LOG_LEVEL: !Ref LogLevel

  3CXOutboundCallFunction:
      Type: AWS::Serverless::Function
      Properties:
        CodeUri: hotelito/3cx/outbound_call/
        Handler: main
        Runtime: go1.x
        Architectures:
          - x86_64
        Events:
          PostOutboundCall:
            Type: Api
            Properties:
              Path: /api/v1/3cx/outbound_call
              Method: POST
        Policies:
              - Version: '2012-10-17'
                Statement:
                  - Effect: Allow
                    Action:
                      - s3:GetObject
                      - s3:PutObject
                    Resource: !Sub 'arn:aws:s3:::${S3BucketMap3CXRoomExtClBedsRoomId}/*'
              - Version: '2012-10-17'
                Statement:
                  - Effect: Allow
                    Action:
                      - ssm:GetParameter
                      - ssm:PutParameter
                      - ssm:DeleteParameter
                    Resource: !Sub 'arn:aws:ssm:${AWS::Region}:*:parameter/${ApplicationName}/${Environment}/*'
        Environment:
          Variables:
            ENVIRONMENT: !Ref Environment
            APPLICATION_NAME: !Ref ApplicationName
            LOG_LEVEL: !Ref LogLevel
            AWS_S3_BUCKET_4_MAP_3CXROOMEXT_CLBEDSROOMID: !Ref S3BucketMap3CXRoomExtClBedsRoomId

Outputs:
  # ServerlessRestApi is an implicit API created out of Events key under Serverless::Function
  # Find out more about other implicit resources you can reference within SAM
  # https://github.com/awslabs/serverless-application-model/blob/master/docs/internals/generated_resources.rst#api
  HotelitoAPI:
    Description: "API Gateway endpoint URL for Prod environment for Hotelito integration Function"
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/"
  CallbackFunction:
    Description: "Hotelito CallbackFunction Lambda Function ARN"
    Value: !GetAtt CallbackFunction.Arn
  HotelitoFunctionIamRole:
    Description: "Implicit IAM Role created for Hotelito function"
    Value: !GetAtt CallbackFunction.Arn
