AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  hotelito-go1.x
  
  SAM Template for hotelito-go1.x

# More info about Globals: https://github.com/awslabs/serverless-application-model/blob/master/docs/globals.rst
Globals:
  Function:
    Timeout: 5
    MemorySize: 128

Resources:

  MyBucket:
      Type: AWS::S3::Bucket
      Properties:
        BucketName: hotelito-app-3cxroomextension-cloudbedsroomid

  InitialAuthorizationFunction:
      Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
      Properties:
        CodeUri: hotelito/cloudbeds/initial_authorization
        Handler: main
        Runtime: go1.x
        Architectures:
          - x86_64
        Events:
          GetInitialAuthorization:
            Type: Api # More info about API Event Source: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#api
            Properties:
              Path: /
              Method: GET
        Environment: # More info about Env Vars: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#environment-object
          Variables:
            ENVIRONMENT: ''
            APPLICATION_NAME: ''
            LOG_LEVEL: ''
            CLOUDBEDS_CLIENT_ID: ''
            CLOUDBEDS_CLIENT_SECRET: ''
            CLOUDBEDS_REDIRECT_URL: ''
            CLOUDBEDS_SCOPES: ''
            CLOUDBEDS_AUTH_URL: ''
            CLOUDBEDS_TOKEN_URL: ''
            CLOUDBEDS_PHONE2ROOM_MAP_FILENAME: ''
            AWS_REGION: ''


  CallbackFunction:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      CodeUri: hotelito/cloudbeds/oauth2callback/
      Handler: main
      Runtime: go1.x
      Architectures:
        - x86_64
      Events:
        GetCallback:
          Type: Api # More info about API Event Source: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#api
          Properties:
            Path: /callback
            Method: GET
      Environment: # More info about Env Vars: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#environment-object
        Variables:
          ENVIRONMENT: ''
          APPLICATION_NAME: ''
          LOG_LEVEL: ''
          CLOUDBEDS_CLIENT_ID: ''
          CLOUDBEDS_CLIENT_SECRET: ''
          CLOUDBEDS_REDIRECT_URL: ''
          CLOUDBEDS_SCOPES: ''
          CLOUDBEDS_AUTH_URL: ''
          CLOUDBEDS_TOKEN_URL: ''
          CLOUDBEDS_PHONE2ROOM_MAP_FILENAME: ''
          AWS_REGION: ''

  3CXLookupByNumberFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: hotelito/3cx/lookupbynumber/
      Handler: main
      Runtime: go1.x
      Architectures:
        - x86_64
      Events:
        GetLookupByNumber:
          Type: Api
          Properties:
            Path: /3cx/lookupbynumber
            Method: GET
      Environment:
        Variables:
          ENVIRONMENT: ''
          APPLICATION_NAME: ''
          LOG_LEVEL: ''
          CLOUDBEDS_CLIENT_ID: ''
          CLOUDBEDS_CLIENT_SECRET: ''
          CLOUDBEDS_REDIRECT_URL: ''
          CLOUDBEDS_SCOPES: ''
          CLOUDBEDS_AUTH_URL: ''
          CLOUDBEDS_TOKEN_URL: ''
          CLOUDBEDS_PHONE2ROOM_MAP_FILENAME: ''
          AWS_REGION: ''

  3CXOutboundCallFunction:
      Type: AWS::Serverless::Function
      Properties:
        CodeUri: hotelito/3cx/outbound_call/
        Handler: main
        Runtime: go1.x
        Architectures:
          - x86_64
        Events:
          PostOutboundCall:
            Type: Api
            Properties:
              Path: /3cx/outbound_call
              Method: POST
        Policies:
                - Version: '2012-10-17'
                  Statement:
                    - Effect: Allow
                      Action:
                        - s3:GetObject
                        - s3:PutObject
                      Resource: !Sub arn:aws:s3:::hotelito-app-3cxroomextension-cloudbedsroomid/*
        Environment:
          Variables:
            ENVIRONMENT: ''
            APPLICATION_NAME: ''
            LOG_LEVEL: ''
            CLOUDBEDS_CLIENT_ID: ''
            CLOUDBEDS_CLIENT_SECRET: ''
            CLOUDBEDS_REDIRECT_URL: ''
            CLOUDBEDS_SCOPES: ''
            CLOUDBEDS_AUTH_URL: ''
            CLOUDBEDS_TOKEN_URL: ''
            CLOUDBEDS_PHONE2ROOM_MAP_FILENAME: ''
            AWS_REGION: ''

Outputs:
  # ServerlessRestApi is an implicit API created out of Events key under Serverless::Function
  # Find out more about other implicit resources you can reference within SAM
  # https://github.com/awslabs/serverless-application-model/blob/master/docs/internals/generated_resources.rst#api
  HotelitoAPI:
    Description: "API Gateway endpoint URL for Prod environment for Hotelito integration Function"
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/"
  CallbackFunction:
    Description: "Hotelito CallbackFunction Lambda Function ARN"
    Value: !GetAtt CallbackFunction.Arn
  HotelitoFunctionIamRole:
    Description: "Implicit IAM Role created for Hotelito function"
    Value: !GetAtt CallbackFunction.Arn
