name: build

on:
  push:
    branches: [ standalone-dev, master ]
    tags:
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      MY_WORKDIR: ./app/hotelito

    steps:
      - name: set up go 1.20
        uses: actions/setup-go@v4
        with:
          go-version: "1.20"
        id: go

      - name: checkout
        uses: actions/checkout@v3
      
      - name: Get dependencies
        working-directory: ${{ env.MY_WORKDIR }}
        run: go get -v -t -d ./...

      - name: go test
        working-directory: ${{ env.MY_WORKDIR }}
        run: |
          go test -v -timeout=100s -covermode=count -coverprofile=profile.cov ./...

      - name: golangci-lint
        uses: golangci/golangci-lint-action@v3
        with:
          version: latest
          working-directory: ${{ env.MY_WORKDIR }}

    #   - name: install goveralls
    #     run: |
    #       curl -sfL https://raw.githubusercontent.com/golangci/golangci-lint/master/install.sh| sh -s -- -b $GITHUB_WORKSPACE v1.45.0
    #       GO111MODULE=off go get -u -v github.com/mattn/goveralls

      - name: submit coverage to Coveralls
        uses: shogo82148/actions-goveralls@v1.7.0
        with:
            path-to-profile: ${{ env.MY_WORKDIR }}/profile.cov
            parallel: true
            working-directory: ${{ env.MY_WORKDIR }}

      # - name: submit coverage
      #   run: $(go env GOPATH)/bin/goveralls -service="github" -coverprofile=$GITHUB_WORKSPACE/profile.cov
      #   env:
      #     COVERALLS_TOKEN: ${{ secrets.GITHUB_TOKEN }}