name: build

on:
  push:
    branches: [ standalone-dev, master ]
    tags:
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: set up go 1.20
        uses: actions/setup-go@v4
        with:
          go-version: "1.20"
        id: go

      - name: checkout
        uses: actions/checkout@v3
      
      - name: Get dependencies
        run: go get -v -t -d ./...

      - name: go test
        run: |
          go test -v -timeout=100s -covermode=count -coverprofile=profile.cov ./...

      - name: golangci-lint
        uses: golangci/golangci-lint-action@v3
        with:
          version: latest

      - name: Install goveralls
        run: go install github.com/mattn/goveralls@latest

      - name: Send coverage
        env:
          COVERALLS_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: goveralls -coverprofile=profile.cov -service=github